version: '3'
services:
  angular-patient-portal:
    build: .
    ports:
      - 80:80
    environment:
       - apiUrl=$backendUrl
    image:
      'repo.vaadin.com:5001/angular-patient-portal:node'
